Update README.md

diff --git a/tempfornow/my_stuff_Drivers b/tempfornow/my_stuff_Drivers
--- a/tempfornow/my_stuff_Drivers
+++ b/tempfornow/my_stuff_Drivers
@@ -9,55 +9,29 @@ if ! test_if_my_stuff_lib_sourced 2>/dev/null; then
 	my_stuff_lib_location="$(find $HOME -type f -name ${lib_file_name} | head -1 || :)"
 	if [[ ! -z "${my_stuff_lib_location}" ]];then
 		mv "${my_stuff_lib_location}" "${temp_path}"
-		source "${temp_path}"/${lib_file_name}
-	elif [[ -f "${temp_path}"/${lib_file_name} ]];then
-		if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
-			echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
-			exit 1
-		fi
-	else
+	elif [[ ! -f "${temp_path}"/${lib_file_name} ]];then
 		echo "wget lib file"
-		if wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
-			if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
-				echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
-				exit 1
-			fi
-		else
+		if ! wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
 			echo "Error: Failed to download ${lib_file_name} ."
 			exit 1
 		fi
 	fi
+	if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
+		echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
+		exit 1
+	fi
+	check_if_user_has_root_access
 	fix_time_
-	set_PACKAGE_MANAGER
+	must_install_apps
 fi
 
 install_GPU_now="${1-}"
-list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"
+List_of_apt_2_install_=()
+list_of_apps_file_path=""
 
 ##################################################################################
 # function
 ##################################################################################
-create_apt_list(){
-	apt list 2>/dev/null > "${list_of_apps_file_path}" 
-}
-
-apt_install_(){
-	$__install "${List_of_apt_2_install_[@]}"
-}
-
-add_2_apt_install_(){
-	localarray=("$@")
-
-	for INDEX in "${localarray[@]}"
-	do
-		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
-			if grep "^${INDEX}/" ${list_of_apps_file_path};then
-				List_of_apt_2_install_+=("$INDEX") 
-				show_m "${INDEX} added to install apps" 
-			fi
-		fi
-	done
-}
 
 create_20_intel_conf_file(){
 	show_m "Create 20-intel.conf file."
@@ -112,15 +86,15 @@ if [[ "${install_GPU_now}" = "install_GPU" ]];then
 		if [ "${nvidia_gpu_exist}" = "true" ];then
 			_cuda_="${2-}"
 			_kernel_open_dkms_="${3-}"
-			add_2_apt_install_ "nvidia-driver nvidia-smi nvidia-settings $_kernel_open_dkms_ $_cuda_"
+			add_packages_2_install_list "nvidia-driver nvidia-smi nvidia-settings $_kernel_open_dkms_ $_cuda_"
 		fi
 		
 		if [ "${amd_gpu_exist}" = "true" ];then
-			add_2_apt_install_ "libgl1-mesa-dri xserver-xorg-video-ati xserver-xorg-video-amdgpu mesa-vulkan-drivers vkbasalt"
+			add_packages_2_install_list "libgl1-mesa-dri xserver-xorg-video-ati xserver-xorg-video-amdgpu mesa-vulkan-drivers vkbasalt"
 		fi
 		
 		if [ "${intel_gpu_exist}" = "true" ];then
-			add_2_apt_install_ "xserver-xorg-video-intel intel-gpu-tools intel-media-va-driver"
+			add_packages_2_install_list "xserver-xorg-video-intel intel-gpu-tools intel-media-va-driver"
 		fi
 	fi
 fi
@@ -128,52 +102,51 @@ fi
 ##################################################################################
 # main
 ##################################################################################
-create_apt_list # needed for add_2_apt_install_
 
 if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
-	add_2_apt_install_ "${install_if_laptop[@]}"
+	add_packages_2_install_list "${install_if_laptop[@]}"
 fi
 
 if [[ "$fingerprint_exist" = true ]];then
-    add_2_apt_install_ "${install_fingerprint[@]}"
+    add_packages_2_install_list "${install_fingerprint[@]}"
 fi
 
 if lspci | egrep -i 'wifi|wireless' 1>/dev/null ;then
-	add_2_apt_install_ "${install_wireless[@]}"
+	add_packages_2_install_list "${install_wireless[@]}"
 fi
 
 if sudo dmesg | grep -i bluetooth 1>/dev/null || sudo lsusb | grep -i bluetooth 1>/dev/null ;then
-	add_2_apt_install_ "${install_bluetooth[@]}"
+	add_packages_2_install_list "${install_bluetooth[@]}"
 fi
 
-add_2_apt_install_ "${install_audio[@]}"
-add_2_apt_install_ "${install_Network[@]}"
-add_2_apt_install_ "${install_autoinstall_firmware[@]}"
+add_packages_2_install_list "${install_audio[@]}"
+add_packages_2_install_list "${install_Network[@]}"
+add_packages_2_install_list "${install_autoinstall_firmware[@]}"
 
 if [[ "${install_GPU_now}" = "install_GPU" ]];then
-	if [ "${nvidia_gpu_exist}" = "true" ];then
-		if [[ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ]];then
-			curl -fSsL "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
-		fi
-		
-		if [[ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ]];then 
-			echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list
+	if [[ $PACKAGER == "apt-get" ]]; then
+		if [ "${nvidia_gpu_exist}" = "true" ];then
+			if [[ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ]];then
+				curl -fSsL "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
+			fi
+			
+			if [[ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ]];then 
+				echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list
+			fi
 		fi
 	fi
 fi
-		
-if [ "$this_is_ubuntu" = true ];then
-	sudo apt-get install -y software-properties-common
-	sudo add-apt-repository -y universe
-	sudo add-apt-repository -y multiverse
+
+if [[ $PACKAGER == "apt-get" ]]; then		
+	if [ "$this_is_ubuntu" = true ];then
+		sudo apt-get install -y software-properties-common
+		sudo add-apt-repository -y universe
+		sudo add-apt-repository -y multiverse
+	fi
 	show_m "Running Update."
-	aptupdate
-else
-	show_m "Running Update."
-	aptupdate
+	aptupdate	
 fi
-		
-apt_install_
+install_packages
 
 if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
 	show_m "this is laptop"
diff --git a/tempfornow/my_stuff_Installapps_list b/tempfornow/my_stuff_Installapps_list
--- a/tempfornow/my_stuff_Installapps_list
+++ b/tempfornow/my_stuff_Installapps_list
@@ -9,26 +9,20 @@ if ! test_if_my_stuff_lib_sourced 2>/dev/null; then
 	my_stuff_lib_location="$(find $HOME -type f -name ${lib_file_name} | head -1 || :)"
 	if [[ ! -z "${my_stuff_lib_location}" ]];then
 		mv "${my_stuff_lib_location}" "${temp_path}"
-		source "${temp_path}"/${lib_file_name}
-	elif [[ -f "${temp_path}"/${lib_file_name} ]];then
-		if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
-			echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
-			exit 1
-		fi
-	else
+	elif [[ ! -f "${temp_path}"/${lib_file_name} ]];then
 		echo "wget lib file"
-		if wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
-			if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
-				echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
-				exit 1
-			fi
-		else
+		if ! wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
 			echo "Error: Failed to download ${lib_file_name} ."
 			exit 1
 		fi
 	fi
+	if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
+		echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
+		exit 1
+	fi
+	check_if_user_has_root_access
 	fix_time_
-	set_PACKAGE_MANAGER
+	must_install_apps
 fi
 
 ##################################################################################
@@ -63,33 +57,9 @@ for option in "${extra_apps_2_install[@]}";do
 done
 
 List_of_apt_2_install_=()
-
-##################################################################################
-# Functions
-##################################################################################
-
-apt_install_()
-{
-	$__install "${List_of_apt_2_install_[@]}"
-}
-
-add_2_apt_install_()
-{
-	localarray=("$@")
-	
-	for INDEX in "${localarray[@]}"
-	do
-		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
-			check_apps_in_cache="$(grep " $INDEX " "${list_of_apps_file_path}" 2>/dev/null || :)"
-			if [ -n "${check_apps_in_cache}" ];then
-				List_of_apt_2_install_+=("$INDEX") 
-				show_m "${INDEX} added to install apps" 
-			else
-				[ "${localarray[0]}" != "firefox" ] && show_em "failed ${INDEX}."
-			fi
-		fi
-	done
-}
+list_of_apps_file_path=""
+package_firefox="$(check_if_package_exist_in_repo firefox)"
+package_firefox_esr="$(check_if_package_exist_in_repo firefox-esr)"
 
 ##################################################################################
 ## must_install_apps_list
@@ -100,7 +70,7 @@ install_must_have_apps2=(psmisc unzip dunst xorg arandr autorandr dbus-x11 pnmix
 install_openbox_=(openbox obconf xcape tint2 nitrogen)
 install_image_viewer_apps=(viewnior)
 install_files_manager_app=(thunar thunar-archive-plugin gvfs gvfs-fuse gvfs-backends file-roller ranger meld baobab)
-install_firefox_=(firefox firefox-esr)
+install_firefox_=($package_firefox $package_firefox_esr)
 install_terminal=(kitty terminator)
 install_conky_all_app=(conky-all)
 install_if_laptop=(tlp tlp-rdw powertop xserver-xorg-input-synaptics xinput)
@@ -137,54 +107,49 @@ install_zsh=(zsh zsh-antigen zsh-autosuggestions zsh-syntax-highlighting)
 # main
 ##################################################################################
 
-aptupdate
 upgrade_now
 
-list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"
-show_m "create_list_of_apps"
-apt list 2>/dev/null | awk -F"/" '{print " " $1 " "}' > "${list_of_apps_file_path}"
-
 if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
-	add_2_apt_install_ "${install_if_laptop[@]}"
+	add_packages_2_install_list "${install_if_laptop[@]}"
 fi
-add_2_apt_install_ "${install_themes[@]}"
-add_2_apt_install_ "${install_terminal[@]}"
-add_2_apt_install_ "${install_files_manager_app[@]}"
-add_2_apt_install_ "${install_x_lock_extra[@]}"
-add_2_apt_install_ "${install_firefox_[@]}"
-add_2_apt_install_ "${install_cli_sound_app[@]}"
-add_2_apt_install_ "${install_conky_all_app[@]}"
-add_2_apt_install_ "${install_text_editer_app[@]}"
-add_2_apt_install_ "${install_mediaplayer_app[@]}"
-add_2_apt_install_ "${install_openbox_[@]}"
-add_2_apt_install_ "${install_fonts[@]}"
-add_2_apt_install_ "${install_for_scripts[@]}"
-add_2_apt_install_ "${install_for_script_bl_reload_gtk23[@]}"
-add_2_apt_install_ "${install_image_viewer_apps[@]}"
-add_2_apt_install_ "${install_must_have_apps[@]}"
-add_2_apt_install_ "${install_must_have_apps2[@]}"
-add_2_apt_install_ "${install_polkit_apps[@]}"
-add_2_apt_install_ "${install_better_bash[@]}"
-add_2_apt_install_ "${install_cli_apps[@]}"
+add_packages_2_install_list "${install_themes[@]}"
+add_packages_2_install_list "${install_terminal[@]}"
+add_packages_2_install_list "${install_files_manager_app[@]}"
+add_packages_2_install_list "${install_x_lock_extra[@]}"
+add_packages_2_install_list "${install_firefox_[@]}"
+add_packages_2_install_list "${install_cli_sound_app[@]}"
+add_packages_2_install_list "${install_conky_all_app[@]}"
+add_packages_2_install_list "${install_text_editer_app[@]}"
+add_packages_2_install_list "${install_mediaplayer_app[@]}"
+add_packages_2_install_list "${install_openbox_[@]}"
+add_packages_2_install_list "${install_fonts[@]}"
+add_packages_2_install_list "${install_for_scripts[@]}"
+add_packages_2_install_list "${install_for_script_bl_reload_gtk23[@]}"
+add_packages_2_install_list "${install_image_viewer_apps[@]}"
+add_packages_2_install_list "${install_must_have_apps[@]}"
+add_packages_2_install_list "${install_must_have_apps2[@]}"
+add_packages_2_install_list "${install_polkit_apps[@]}"
+add_packages_2_install_list "${install_better_bash[@]}"
+add_packages_2_install_list "${install_cli_apps[@]}"
 if [[ "$install_xfce4_panel_now" = true ]];then
-	add_2_apt_install_ "${install_xfce4_panel[@]}"
+	add_packages_2_install_list "${install_xfce4_panel[@]}"
 fi
 if [[ "$install_polybar_now" = true ]];then
-	add_2_apt_install_ "${install_polybar[@]}"
+	add_packages_2_install_list "${install_polybar[@]}"
 fi
 if [[ "$install_qt5ct_now" = true ]];then
-	add_2_apt_install_ "${install_qt5ct[@]}"
+	add_packages_2_install_list "${install_qt5ct[@]}"
 fi
 if [[ "$install_jgmenu_now" = true ]];then
-	add_2_apt_install_ "${install_jgmenu[@]}"
+	add_packages_2_install_list "${install_jgmenu[@]}"
 fi
 if [[ "$install_bspwm_now" = true ]];then
-	add_2_apt_install_ "${install_bspwm[@]}"
+	add_packages_2_install_list "${install_bspwm[@]}"
 fi
 if [[ "$install_zsh_now" = true ]];then
-	add_2_apt_install_ "${install_zsh[@]}"
+	add_packages_2_install_list "${install_zsh[@]}"
 fi
-apt_install_
+install_packages
 
 show_m "Configer packages."
 
diff --git a/tempfornow/my_stuff_lib b/tempfornow/my_stuff_lib
--- a/tempfornow/my_stuff_lib
+++ b/tempfornow/my_stuff_lib
@@ -2,15 +2,16 @@
 set -e
 
 Custom_distro_name="My Stuff"
-Custom_distro_dir_name="$(echo "$Custom_distro_name" | tr -dc '[:alnum:] \n\r' | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')"
 [[ -z "${temp_path}" ]] && temp_path="/tmp/my_stuff"
+list_of_apps_file_path="${temp_path}/list_of_apps"
 
+
+
+Custom_distro_dir_name="$(echo "$Custom_distro_name" | tr -dc '[:alnum:] \n\r' | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')"
 _SUDO=""
-
-if command -v sudo >/dev/null;then
-	_SUDO="sudo"
-fi
-
+command -v sudo >/dev/null && _SUDO="sudo"
+PACKAGER=""
+__noninteractive=""
 __noninteractive_install=""
 __install=""
 __purge=""
@@ -98,48 +99,18 @@ check_and_download_()
 	fi
 }
 
-aptupdate()
-{
-	show_m "updating your system"
-	if ! command -v sudo >/dev/null
-	then
-		[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || apt-get update
-		apt-get update
-	else
-		[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || sudo apt-get update
-		sudo apt-get update
-	fi
-}
-
-aptfixer()
-{
-	if ! command -v sudo >/dev/null
-	then
-		if grep 'deb cdrom' /etc/apt/sources.list;then
-			sed -i '/deb cdrom/d' /etc/apt/sources.list
-		fi
-	else
-		if grep 'deb cdrom' /etc/apt/sources.list;then
-			sudo sed -i '/deb cdrom/d' /etc/apt/sources.list
-		fi
-	fi
-	
-	aptupdate
-	
-	### Fix broken packages for good measure (why not?)
-	$__install -f 2>/dev/null || show_em "failed to $__install -f"
-}
-
 check_for_SUDO()
 {
 	if ! command -v sudo >/dev/null;then
 		show_m "Install sudo and add user 1000 to sudo group"
-		set_PACKAGE_MANAGER
 		kill_PACKAGE_MANAGER && $__install sudo || (kill_PACKAGE_MANAGER && $__install sudo) || (show_em "failed to install sudo" && exit 1)
 		user=$(cut -f 1,3 -d: /etc/passwd | grep :1000$ | cut -f1 -d:)
 		[ "$user" ] && adduser "$user" sudo
 	fi
 	_SUDO="sudo"
+	
+	set_package_manager
+	
 	keep_sudo_refresed(){
 		while true
 		do
@@ -152,6 +123,8 @@ check_for_SUDO()
 
 must_install_apps()
 {
+	check_for_SUDO
+	
 	if ! command -v killall >/dev/null;then
 		($__install psmisc && kill_PACKAGE_MANAGER) || ($__install psmisc && kill_PACKAGE_MANAGER) || $__install psmisc
 		exval=$?
@@ -174,46 +147,6 @@ must_install_apps()
 		if [ "$exval" == "1" ]; then
 			(show_em "failed to install git.")
 		fi
-	fi
-}
-
-kill_PACKAGE_MANAGER()
-{
-	sudo killall -9 apt &>/dev/null || sudo killall -9 apt-get &>/dev/null || :
-}
-
-upgrade_now()
-{
-	sudo DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
-}
-
-full_upgrade_now()
-{
-	sudo DEBIAN_FRONTEND=noninteractive apt-get -y full-upgrade
-}
-
-_unattended_upgrades_()
-{
-	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
-	if [ -f "${auto_upgrades_file}" ];then
-		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
-		case "$1" in
-			start)
-					sudo systemctl stop unattended-upgrades || :
-				if [ ! -f "${auto_upgrades_file_bak}" ];then
-					sudo mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
-				fi
-			;;
-			stop)
-				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
-					sudo rm "${auto_upgrades_file}"
-				fi
-					
-				if [ -f "${auto_upgrades_file_bak}" ];then
-					sudo mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
-				fi
-			;;
-		esac
 	fi
 }
 
@@ -276,47 +209,29 @@ git_clone_and_set_var_to_path(){
 	echo "${getthis_location}"
 }
 
-set_PACKAGE_MANAGER() {
-	PACKAGER=""
-	## Check Package Handeler
-    PACKAGEMANAGER='apt-get yum dnf pacman zypper'
-    for pgm in ${PACKAGEMANAGER}; do
-        if command -v ${pgm} >/dev/null; then
-            PACKAGER=${pgm}
-            echo -e "Using ${pgm}"
-            break
-        fi
-    done
-
-    if [ -z "${PACKAGER}" ]; then
-        echo -e "${RED}Can't find a supported package manager"
-        exit 1
-    fi
-    
-    if [[ $PACKAGER == "pacman" ]]; then
-        if ! command -v yay >/dev/null && ! command -v paru >/dev/null; then
-            echo "Installing yay as AUR helper..."
-            $_SUDO ${PACKAGER} --noconfirm -S base-devel
-            cd /opt && sudo git clone https://aur.archlinux.org/yay-git.git && sudo chown -R ${USER}:${USER} ./yay-git
-            cd yay-git && makepkg --noconfirm -si
-        else
-            echo "Aur helper already installed"
-        fi
-        if command -v yay >/dev/null; then
-            AUR_HELPER="yay --noconfirm -S"
-        elif command -v paru >/dev/null; then
-            AUR_HELPER="paru --noconfirm -S"
-        else
-            echo "No AUR helper found. Please install yay or paru."
-            exit 1
-        fi
-    else
-    	__noninteractive="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
-    	__noninteractive_install='$_SUDO DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq'
-		__install="$_SUDO ${PACKAGER} install -yq "
-		__purge="$_SUDO apt-get purge -y"
-		aptfixer
-    fi
+_unattended_upgrades_()
+{
+	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
+	if [ -f "${auto_upgrades_file}" ];then
+		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
+		case "$1" in
+			start)
+				sudo systemctl stop unattended-upgrades || :
+				if [ ! -f "${auto_upgrades_file_bak}" ];then
+					sudo mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
+				fi
+			;;
+			stop)
+				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
+					sudo rm "${auto_upgrades_file}"
+				fi
+					
+				if [ -f "${auto_upgrades_file_bak}" ];then
+					sudo mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
+				fi
+			;;
+		esac
+	fi
 }
 
 fix_time_(){
@@ -337,6 +252,26 @@ fix_time_(){
 	fi
 }
 
+check_if_user_has_root_access(){
+    ## Check SuperUser Group
+    SUPERUSERGROUP='wheel sudo root'
+    for sug in ${SUPERUSERGROUP}; do
+        if groups | grep ${sug} >/dev/null; then
+            SUGROUP=${sug}
+            echo -e "Super user group ${SUGROUP}"
+        fi
+    done
+
+    ## Check if member of the sudo group.
+    if ! groups | grep ${SUGROUP} >/dev/null; then
+        echo -e "\e[31m You need to be a member of the sudo group to run me!"
+        exit 1
+    fi
+    
+    if command -v sudo >/dev/null;then
+		sudo -v
+	fi
+}
 ######################################################################################################################
 ######################################################################################################################
 ######################################################################################################################
@@ -412,3 +347,193 @@ CHECK_IF_THIS_LAPTOP(){
 	fi
 	echo ${is_this_laptop}
 }
+
+######################################################################################################################
+# set package manager var and functions
+######################################################################################################################
+
+set_package_manager(){
+	## Check Package Handeler
+	PACKAGEMANAGER='apt-get yum dnf pacman zypper'
+	for pgm in ${PACKAGEMANAGER}; do
+		if command -v ${pgm} >/dev/null; then
+			PACKAGER=${pgm}
+			echo -e "Using ${pgm}"
+			break
+		fi
+	done
+	
+	if [ -z "${PACKAGER}" ]; then
+		echo -e "${RED}Can't find a supported package manager"
+		exit 1
+	fi
+    	
+	if [[ $PACKAGER == "pacman" ]]; then
+		if ! command -v yay >/dev/null && ! command -v paru >/dev/null; then
+			echo "Installing yay as AUR helper..."
+			$_SUDO ${PACKAGER} --noconfirm -S base-devel
+			cd /opt && sudo git clone https://aur.archlinux.org/yay-git.git && sudo chown -R ${USER}:${USER} ./yay-git
+			cd yay-git && makepkg --noconfirm -si
+		else
+			echo "Aur helper already installed"
+		fi
+		if command -v yay >/dev/null; then
+			PACKAGER="yay"
+		elif command -v paru >/dev/null; then
+			PACKAGER="paru"
+		else
+			echo "No AUR helper found. Please install yay or paru."
+			exit 1
+		fi
+		echo -e "switching ${PACKAGER}"
+	fi
+	
+	if [[ $PACKAGER == "apt-get" ]]; then
+		__noninteractive="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
+		__noninteractive_install='$_SUDO DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq'
+		__install="$_SUDO ${PACKAGER} install -yq"
+		__purge="$_SUDO ${PACKAGER} purge -y"
+	elif [[ $PACKAGER == "yay" ]] || [[ $PACKAGER == "paru" ]]; then
+		__noninteractive="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
+		__noninteractive_install='$_SUDO DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq'
+		__install="${PACKAGER} --noconfirm -S"
+		__purge="$_SUDO ${PACKAGER} purge -y"
+	elif [[ $PACKAGER == "yum" ]]; then
+		__install="$_SUDO ${PACKAGER} install -yq"
+	elif [[ $PACKAGER == "dnf" ]]; then
+		__install="$_SUDO ${PACKAGER} install -yq"
+	elif [[ $PACKAGER == "zypper" ]]; then
+		__install="$_SUDO ${PACKAGER} install -yq"
+	fi
+}
+
+set_package_manager
+
+if [[ $PACKAGER == "apt-get" ]]; then
+	# create list_of_apps file
+	show_m "create_list_of_apps"
+	apt list 2>/dev/null > "${list_of_apps_file_path}"
+	# functions
+	create_package_list(){
+		if [[ -z "${list_of_apps_file_path}" ]];then
+			show_m "create_list_of_apps"
+			list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"
+			apt list 2>/dev/null | awk -F/ '{print " " $1 " " }' > "${list_of_apps_file_path}" 
+		fi
+	}
+	
+	install_packages(){
+		$__install "${List_of_apt_2_install_[@]}"
+	}
+	
+	check_if_package_exist_in_repo(){
+		local package_name="${1-}"
+		if ! dpkg -s "${package_name}" > /dev/null 2>&1; then
+			check_apps_in_cache="$(grep "^$package_name/" "${list_of_apps_file_path}" 2>/dev/null || :)"
+			if [ -n "${check_apps_in_cache}" ];then
+				echo "${package_name}" 
+			fi
+		fi
+	}
+	
+	add_packages_2_install_list()
+	{
+		localarray=("$@")
+		
+		for INDEX in "${localarray[@]}"
+		do
+			if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
+				check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
+				if [ -n "${check_apps_in_cache}" ];then
+					List_of_apt_2_install_+=("$INDEX") 
+					show_m "${INDEX} added to install apps" 
+				fi
+			fi
+		done
+	}
+	aptupdate(){
+		show_m "updating your system"
+		[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || $_SUDO ${PACKAGER} update
+	}
+	aptfixer(){
+			if ! command -v sudo >/dev/null
+			then
+				if grep 'deb cdrom' /etc/apt/sources.list;then
+					sed -i '/deb cdrom/d' /etc/apt/sources.list
+				fi
+			else
+				if grep 'deb cdrom' /etc/apt/sources.list;then
+					$_SUDO sed -i '/deb cdrom/d' /etc/apt/sources.list
+				fi
+			fi
+			aptupdate
+			### Fix broken packages for good measure (why not?)
+			$__install -f 2>/dev/null || show_em "failed to $__install -f"
+	}	
+		
+	kill_PACKAGE_MANAGER(){
+		$_SUDO killall -9 apt &>/dev/null || $_SUDO killall -9 ${PACKAGER} &>/dev/null || :
+	}
+		
+	upgrade_now()
+	{
+		$_SUDO ${__noninteractive} ${PACKAGER} -y upgrade
+		$_SUDO ${__noninteractive} ${PACKAGER} -y full-upgrade
+	}
+	enable_repo_contrib(){
+	(
+	IFS=$'\n'
+		for l in $deb_lines_contrib; do
+			$_SUDO sed -i "s\\^$l$\\$l contrib\\" /etc/apt/sources.list
+		done
+	)
+	}
+	enable_repo_nonfree_firmware(){
+	(
+	IFS=$'\n'
+		for l in $deb_lines_nonfree_firmware; do
+			$_SUDO sed -i "s\\^$l$\\$l nonfreefirmware\\" /etc/apt/sources.list
+		done
+		$_SUDO sed -i 's/nonfreefirmware/non-free-firmware/g'  /etc/apt/sources.list
+	)
+	}
+	enable_repo_nonfree(){
+	(
+	IFS=$'\n'
+		for l in $deb_lines_nonfree; do
+			$_SUDO sed -i "s\\^$l$\\$l nonfreeonly\\" /etc/apt/sources.list
+		done
+		$_SUDO sed -i 's/nonfreeonly/non-free/g'  /etc/apt/sources.list
+	)
+	}
+	enable_repo_(){
+		local update_now=false
+		if [[ "$enable_contrib" = true ]];then
+			enable_repo_contrib && update_now=true
+		fi
+		if [[ "$enable_nonfree_firmware" = true ]];then
+			enable_repo_nonfree_firmware && update_now=true
+		fi
+		if [[ "$enable_nonfree" = true ]];then
+			enable_repo_nonfree && update_now=true
+		fi
+	}
+	aptfixer
+	enable_repo_
+elif [[ $PACKAGER == "yay" ]] || [[ $PACKAGER == "paru" ]]; then
+	# create list_of_apps file
+	show_m "create_list_of_apps"
+	apt list 2>/dev/null > "${list_of_apps_file_path}"
+elif [[ $PACKAGER == "yum" ]]; then
+	# create list_of_apps file
+	show_m "create_list_of_apps"
+	apt list 2>/dev/null > "${list_of_apps_file_path}"
+elif [[ $PACKAGER == "dnf" ]]; then
+	# create list_of_apps file
+	show_m "create_list_of_apps"
+	apt list 2>/dev/null > "${list_of_apps_file_path}"
+elif [[ $PACKAGER == "zypper" ]]; then
+	# create list_of_apps file
+	show_m "create_list_of_apps"
+	apt list 2>/dev/null > "${list_of_apps_file_path}"
+fi
