Update README.md

diff --git a/tempfornow/my_stuff_lib b/tempfornow/my_stuff_lib
--- a/tempfornow/my_stuff_lib
+++ b/tempfornow/my_stuff_lib
@@ -80,17 +80,19 @@ show_em()
 check_and_download_()
 {
 	check_this_file_="${1-}"
+	new_check_this_file_="${temp_path}/${check_this_file_}"
 	check_this_file_location="$(find $HOME -type f -name ${check_this_file_} | head -1)"
+	
 	if [[ ! -z "${check_this_file_location}" ]];then
 		mv "${check_this_file_location}" "${temp_path}"
 	fi
-
-	if [[ ! -f "${temp_path}/${check_this_file_}" ]]; then
+	
+	if [[ ! -f "${new_check_this_file_}" ]]; then
 	show_m "Wget $check_this_file_ file from www.github.com/dari862/my_stuff_installer ."
-		wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/"$check_this_file_" || show_em "Error: Failed to download $check_this_file_ ."
-		chmod +x "$check_this_file_"
-		if [[ ! -f "${temp_path}/${check_this_file_}" ]]; then
-			echo "Error: Failed to wget ${check_this_file_} from ${temp_path}" >&2
+		wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/"$check_this_file_" -O "${new_check_this_file_}" || show_em "Error: Failed to download $check_this_file_ ."
+		chmod +x "${new_check_this_file_}"
+		if [[ ! -f "${new_check_this_file_}" ]]; then
+			echo "Error: Failed to wget ${check_this_file_} from ${new_check_this_file_} " >&2
 			exit 1
 		fi
 	fi
