Update README.md

diff --git a/tempfornow/my_stuff_Installapps_list b/tempfornow/my_stuff_Installapps_list
--- a/tempfornow/my_stuff_Installapps_list
+++ b/tempfornow/my_stuff_Installapps_list
@@ -2,13 +2,18 @@
 set -e
 
 # source lib
-script_fullpath=$(dirname "$(readlink -f "$0")")
-[ "$(echo "${script_fullpath}" | grep "/proc/*")" ] && script_fullpath="/tmp"
-cd "${script_fullpath}"
-if ! . lib 2> /dev/null; then
-	wget -q https://raw.githubusercontent.com/dari862/my_linux/main/tempfornow/lib
-	if ! . lib 2> /dev/null; then
-		echo "Error: Failed to locate lib from ${script_fullpath}" >&2
+temp_path="/tmp"
+
+my_stuff_lib_location="$(find $HOME -type f -name my_stuff_lib | head -1)"
+if [[ ! -z "${my_stuff_lib_location}" ]];then
+	mv "${my_stuff_lib_location}" "${temp_path}"
+fi
+
+if ! source "${temp_path}"/my_stuff_lib 2> /dev/null; then
+	echo "wget lib file"
+	wget -q https://raw.githubusercontent.com/dari862/my_linux/main/tempfornow/my_stuff_lib
+	if ! source "${temp_path}"/my_stuff_lib 2> /dev/null; then
+		echo "Error: Failed to source my_stuff_lib from ${temp_path}" >&2
 		exit 1
 	fi
 fi
@@ -112,14 +117,14 @@ add_2_apt_install_()
 # main
 ##################################################################################
 
-sudo timedatectl set-timezone Asia/Kuwait
-sudo date -s "$(wget --method=HEAD -qSO- --max-redirect=0 google.com 2>&1 | sed -n 's/^ *Date: *//p')" &>/dev/null
+sudo timedatectl set-timezone $__timezone
+sudo date -s "$(wget --method=HEAD -qSO- --max-redirect=0 debian.com 2>&1 | sed -n 's/^ *Date: *//p')" &>/dev/null
 
 aptupdate
 aptfixer
 upgrade_now
 
-list_of_apps_file_path="$(mktemp "${script_fullpath}"/list_of_apps_.XXXXXXXXXXXX)"
+list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"
 show_m "create_list_of_apps"
 apt list 2>/dev/null | awk -F"/" '{print " " $1 " "}' > "${list_of_apps_file_path}"
 
@@ -169,27 +174,27 @@ apt_install_
 if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
 	show_m "this is laptop"
 	show_m "create envycontrol installtion file."
-cat << 'EOF' > /tmp/envycontrol_updater_DmDmDmdMdMdM
-	cd "$(mktemp -d)" 
-	
+cat << 'EOF' > "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
+	envycontrol_updater_path="$(mktemp -d)" 
+	__Custom_distro_dir_name="DmDmDmdMdMdM"
 	wget -qO- 'https://api.github.com/repos/bayasdev/envycontrol/releases/latest' \
   	| grep '"tarball_url"' \
   	| cut -f2,3 -d':' \
   	| tr -d '"' \
   	| tr -d ',' \
-  	| xargs wget -O envycontrol.tar.gz && tar -xvzf envycontrol.tar.gz && mv bayasdev* envycontrol
+  	| xargs wget -O "${envycontrol_updater_path}"/envycontrol.tar.gz && tar -xvzf "${envycontrol_updater_path}"/envycontrol.tar.gz -C "${envycontrol_updater_path}" && mv "${envycontrol_updater_path}"/bayasdev* "${envycontrol_updater_path}"/envycontrol
   	
-  	[ -d "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol" ] && sudo rm -rdf "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol"
-  	[ ! -d "/usr/share/DmDmDmdMdMdM/opt/downloaded" ] && sudo mkdir -p /usr/share/DmDmDmdMdMdM/opt/downloaded
-  	[ ! -d "/usr/share/DmDmDmdMdMdM/opt/git" ] && sudo mkdir -p /usr/share/DmDmDmdMdMdM/opt/git
+  	[ -d "/usr/share/${__Custom_distro_dir_name}/opt/downloaded/envycontrol" ] && sudo rm -rdf "/usr/share/${__Custom_distro_dir_name}/opt/downloaded/envycontrol"
+  	[ ! -d "/usr/share/${__Custom_distro_dir_name}/opt/downloaded" ] && sudo mkdir -p /usr/share/${__Custom_distro_dir_name}/opt/downloaded
+  	[ ! -d "/usr/share/${__Custom_distro_dir_name}/opt/git" ] && sudo mkdir -p /usr/share/${__Custom_distro_dir_name}/opt/git
   	
-  	if [ -d envycontrol ];then
-  		chmod +x ./envycontrol/envycontrol.py 
-  		sudo mv envycontrol "/usr/share/DmDmDmdMdMdM/opt/git/"
-  		ln -sf "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol/envycontrol.py" "/usr/share/DmDmDmdMdMdM/bin/bin/envycontrol"
+  	if [ -d "${envycontrol_updater_path}"/envycontrol ];then
+  		chmod +x "${envycontrol_updater_path}"/envycontrol/envycontrol.py 
+  		sudo mv "${envycontrol_updater_path}"/envycontrol "/usr/share/${__Custom_distro_dir_name}/opt/git/"
+  		ln -sf "/usr/share/${__Custom_distro_dir_name}/opt/downloaded/envycontrol/envycontrol.py" "/usr/share/${__Custom_distro_dir_name}/bin/bin/envycontrol"
   	fi
 EOF
-	chmod +x /tmp/envycontrol_updater_DmDmDmdMdMdM
+	chmod +x "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
 fi
 
 show_m "Configer packages."
diff --git a/tempfornow/my_stuff_lib b/tempfornow/my_stuff_lib
--- a/tempfornow/my_stuff_lib
+++ b/tempfornow/my_stuff_lib
@@ -3,23 +3,7 @@ set -e
 
 Custom_distro_name="My Stuff"
 Custom_distro_dir_name="$(echo "$Custom_distro_name" | tr -dc '[:alnum:] \n\r' | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')"
-
-repo_name="my_stuff_installer"
-repo_name2="my_stuff"
-script_fullpath="$(dirname "$(readlink -f "$0")")"
-
-if echo "${script_fullpath}" | grep  "${repo_name}" &>/dev/null ; then
-	repo_path="$(echo "${script_fullpath}" | awk -F "${repo_name}" '{print $1}' )"
-	if [[ $(ls "$repo_path/${repo_name2}" 2>/dev/null) ]] ;then
-		wget_git_path="${repo_path}"
-	elif [[ $(ls "$repo_path"/../../"${repo_name2}" 2>/dev/null) ]] ;then
-		wget_git_path="$(cd "${repo_path}"/../.. && pwd)"
-	else
-		wget_git_path="/tmp"
-	fi
-else
-	wget_git_path="/tmp"
-fi
+temp_path="/tmp"
 
 declare -a to_be_purged=(
 aisleriot
@@ -77,6 +61,10 @@ xfce4-power-manager*
 
 sudoaptinstall='sudo apt-get install -y'
 aptinstall='apt-get install -y'
+
+#__timezone="$(curl -q https://ipinfo.io/ 2>/dev/null | grep timezone | awk -F: '{print $2}' | sed 's/"//g;s/,//g;s/ //g')"
+__timezone="Asia/Kuwait"
+
 ##################################################################################
 ##################################################################################
 
@@ -92,18 +80,23 @@ show_em()
 	echo "$__massage"
 }
 
-check_and_run_else_download_and_run()
+check_and_download_()
 {
-  check_this_file_="${1-}"
-  if [ ! -f "$check_this_file_" ]; then
-  	show_m "Wget $check_this_file_ file from www.github.com/dari862/my_stuff_installer ."
-	wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/"$check_this_file_" || show_em "Error: Failed to download $check_this_file_ ."
-	chmod +x "$check_this_file_"
-	if [ ! -f "$check_this_file_" ]; then
-		show_em "Error: Failed to locate $check_this_file_ ."
-		exit 1
+	check_this_file_="${1-}"
+	check_this_file_location="$(find $HOME -type f -name ${check_this_file_} | head -1)"
+	if [[ ! -z "${check_this_file_location}" ]];then
+		mv "${check_this_file_location}" "${temp_path}"
 	fi
-fi
+
+	if [[ ! -f "${temp_path}/${check_this_file_}" ]]; then
+	show_m "Wget $check_this_file_ file from www.github.com/dari862/my_stuff_installer ."
+		wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/"$check_this_file_" || show_em "Error: Failed to download $check_this_file_ ."
+		chmod +x "$check_this_file_"
+		if [[ ! -f "${temp_path}/${check_this_file_}" ]]; then
+			echo "Error: Failed to wget ${check_this_file_} from ${temp_path}" >&2
+			exit 1
+		fi
+	fi
 }
 
 aptupdate()
@@ -262,6 +255,27 @@ do_you_want_2_run_this_yes_or_no(){
 	[ "$yn" = "YES" ] && yn="Y"
 	echo "$yn"
 }
+
+git_clone_and_set_var_to_path(){
+	getthis="${1-}"
+	show_m "git clone ${getthis}"
+	getthis_location="$(find $HOME -type d -name ${getthis} | head -1)"
+	
+	if [[ -z "${getthis_location}" ]];then
+		getthis_location="${temp_path}"
+	else
+		getthis_location="$(cd "${getthis_location}" && cd .. && pwd)"
+	fi
+	
+	if [ ! -d "${getthis_location}/${getthis}" ]; then 
+		git clone --depth=1 "https://github.com/dari862/${getthis}.git" "${getthis_location}/${getthis}"
+	else
+		show_m "${getthis} Folder does exsist"
+	fi
+	
+	echo "${getthis_location}"
+}
+
 ######################################################################################################################
 ######################################################################################################################
 ######################################################################################################################
