Update README.md

diff --git a/tempfornow/my_stuff_lib b/tempfornow/my_stuff_lib
--- a/tempfornow/my_stuff_lib
+++ b/tempfornow/my_stuff_lib
@@ -318,6 +318,25 @@ set_PACKAGE_MANAGER() {
 		aptfixer
     fi
 }
+
+fix_time_(){
+	get_date_from_here=""
+	list_to_test=(debian.com github.com 104.16.132.229)
+	
+	for test in "${list_to_test[@]}";do
+		ping -c 1 $test &>/dev/null && get_date_from_here="$test" && break
+	done
+		
+	if [[ -z "$get_date_from_here" ]];then 
+		echo "failed to ping all of this: ${list_to_test[@]}" && exit 1
+	else
+		$_SUDO date -s "$(wget --method=HEAD -qSO- --max-redirect=0 $get_date_from_here 2>&1 | sed -n 's/^ *Date: *//p')" &>/dev/null
+		#__timezone="$(curl -q https://ipinfo.io/ 2>/dev/null | grep timezone | awk -F: '{print $2}' | sed 's/"//g;s/,//g;s/ //g')"
+		__timezone="Asia/Kuwait"
+		$_SUDO timedatectl set-timezone $__timezone	
+	fi
+}
+
 ######################################################################################################################
 ######################################################################################################################
 ######################################################################################################################
