Update README.md

diff --git a/core/disto_package_manager_apt-get b/core/disto_package_manager_apt-get
--- a/core/disto_package_manager_apt-get
+++ b/core/disto_package_manager_apt-get
@@ -1,11 +1,12 @@
 #!/bin/bash
 set -e
 
+remove_aria2=false
 ##################################
 # only for apt
 ##################################
 aptupdate(){
-	show_m "updating your system"
+	show_im "updating your system"
 	[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || $_SUPERUSER apt-get update
 }
 
@@ -97,21 +98,18 @@ enable_repo_(){
 	fi
 }
 
-aptfixer
-enable_repo_
-install_apt_fast || :
-
-if command -v apt-get &>/dev/null;then
-	PACKAGER="apt-get"
-elif command -v apt-fast &>/dev/null;then
-	PACKAGER="apt-fast"
-fi
 ##################################
 # for rest
 ##################################
 
 install_lightdm_now(){
+	if [ -f "${installer_phases}/install_lightdm_now" ];then
+		return
+	fi
+	
 	install_lightdm_=(lightdm lightdm-gtk-greeter-settings)
+	show_im "installing ( lightdm )."
+	
 	if [ -f "/etc/X11/default-display-manager" ]; then
 		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
 		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
@@ -122,16 +120,19 @@ install_lightdm_now(){
 	if [ "$lightdm_does_not_exist" = true  ];then
 		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} && kill_package_ apt-get) || \
 		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} && kill_package_ apt-get) || \
-		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]}
-		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1
-		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm
+		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} || (show_em "failed to install lightdm")
+		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1 || (show_em "failed to change default-display-manager")
+		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm || (show_em "failed to dpkg-reconfigure lightdm")
+	else
+		show_im "lightdm already exist."
 	fi
+	touch "${installer_phases}/install_lightdm_now"
 }
 
 create_package_list(){
 	# create list_of_apps file
 	if [[ ! -f "${list_of_apps_file_path}" ]];then
-		show_m "create_list_of_apps"
+		show_im "create_list_of_apps"
 		apt list 2>/dev/null > "${list_of_apps_file_path}" 
 	fi
 }
@@ -162,9 +163,9 @@ add_packages_2_install_list()
 			check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
 			if [ -n "${check_apps_in_cache}" ];then
 				List_of_apt_2_install_+=("$INDEX") 
-				show_m "${INDEX} added to install apps" 
+				show_im "${INDEX} added to install apps" 
 			else
-				show_em "${INDEX} does not exist." 
+				show_wm "${INDEX} does not exist." 
 			fi
 		fi
 	done
@@ -183,24 +184,72 @@ remove_package_with_error2info()
 	for package in "${localarray[@]}"
 	do
 		if dpkg -s "${package}" &>/dev/null; then
-			show_m "Purging ${package}."
+			show_im "Purging ${package}."
 			$_SUPERUSER apt-get purge -y "$package"
 		fi
 	done
 }
 
 remove_unnecessary_package_manager_stuff(){
-	show_m "removing apt-fast and conf"
-	[ "$remove_aria2" = true ] && show_m "removing aria2 package" && $_SUPERUSER apt-get purge -y aria2
-	[ -f /usr/local/bin/apt-fast ] && show_m "removing apt-fast" && $_SUPERUSER rm -f /usr/local/bin/apt-fast
-	[ -f /etc/apt-fast.conf ] && show_m "removing apt-fast.conf" && $_SUPERUSER rm -f /etc/apt-fast.conf
+	show_im "removing apt-fast and conf"
+	[ "$remove_aria2" = true ] && show_im "removing aria2 package" && $_SUPERUSER apt-get purge -y aria2
+	[ -f /usr/local/bin/apt-fast ] && show_im "removing apt-fast" && $_SUPERUSER rm -f /usr/local/bin/apt-fast
+	[ -f /etc/apt-fast.conf ] && show_im "removing apt-fast.conf" && $_SUPERUSER rm -f /etc/apt-fast.conf
 }
 
 run_package_manager_autoclean(){
-	show_m "autoremove unwanted pakages"
+	show_im "autoremove unwanted pakages"
 	$_SUPERUSER apt-get autoremove -y
 	$_SUPERUSER apt-get autoclean -y
 }
 
-upgrade_now
-create_package_list
+_unattended_upgrades_()
+{
+	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
+	if [ -f "${auto_upgrades_file}" ];then
+		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
+		case "$1" in
+			start)
+				if [ -f "${installer_phases}/_unattended_upgrades_start" ];then
+					return
+				fi
+				show_im "start unattended upgrades."
+				init_manager stop unattended-upgrades || :
+				if [ ! -f "${auto_upgrades_file_bak}" ];then
+					my-superuser mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
+				fi
+				touch "${installer_phases}/_unattended_upgrades_start"
+			;;
+			stop)
+				if [ -f "${installer_phases}/_unattended_upgrades_stop" ];then
+					return
+				fi
+				show_im "stop unattended upgrades."
+				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
+					my-superuser rm "${auto_upgrades_file}"
+				fi
+					
+				if [ -f "${auto_upgrades_file_bak}" ];then
+					my-superuser mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
+				fi
+				touch "${installer_phases}/_unattended_upgrades_stop"
+			;;
+		esac
+	fi
+}
+
+pre_package_manager_(){
+	init_manager stop apt-daily.timer
+	init_manager stop apt-daily-upgrade.timer
+	aptfixer
+	enable_repo_
+	install_apt_fast || :
+	
+	if command -v apt-get &>/dev/null;then
+		PACKAGER="apt-get"
+	elif command -v apt-fast &>/dev/null;then
+		PACKAGER="apt-fast"
+	fi
+	upgrade_now
+	create_package_list
+}
