Update README.md

diff --git a/core/installer_repo/apt-get b/core/installer_repo/apt-get
--- a/core/installer_repo/apt-get
+++ b/core/installer_repo/apt-get
@@ -22,11 +22,10 @@ aptfixer(){
 
 install_apt_fast(){
 	if ! type aria2c >/dev/null 2>&1;then
-		show_sm "add aria2c to purge list"
+		show_sm "install aria2c."
   		$_SUPERUSER apt-get install -y aria2
-  		remove_aria2=true
 	fi
-	
+	remove_aria2=true
 	show_sm "download apt-fast"
 	apt_fast_url='https://raw.githubusercontent.com/ilikenwf/apt-fast/master'
 	download_file "$_SUPERUSER" "${apt_fast_url}/apt-fast" "/usr/local/bin/apt-fast"
@@ -110,44 +109,25 @@ enable_repo_(){
 ##################################
 # for rest
 ##################################
-install_lightdm_now(){
-	[ -f "${installer_phases}/install_lightdm_now" ] && return
-	
-	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
-	show_im "installing ( lightdm )."
-	
-	if [ -f "/etc/X11/default-display-manager" ];then
-		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
-		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
-	else
-		lightdm_does_not_exist=true
-	fi
-	
-	if [ "$lightdm_does_not_exist" = true  ];then
-		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} && kill_package_ apt-get) || \
-		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} && kill_package_ apt-get) || \
-		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} || (show_em "failed to install lightdm")
-		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1 || (show_em "failed to change default-display-manager")
-		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm || (show_em "failed to dpkg-reconfigure lightdm")
-	else
-		show_im "lightdm already exist."
-	fi
-	touch "${installer_phases}/install_lightdm_now"
-}
 
 create_package_list(){
 	# create list_of_apps file
 	if [ ! -f "${list_of_apps_file_path}" ];then
-		show_im "create_list_of_apps"
+		show_im "Creating package list..."
 		apt list 2>/dev/null > "${list_of_apps_file_path}" 
+	fi
+	
+	if [ ! -f "${list_of_installed_apps_file_path}" ];then
+		show_im "Creating installed package list..."
+		apt list --installed 2>/dev/null > "${list_of_installed_apps_file_path}" 
 	fi
 }
 
 install_packages(){
 	if [ -n "${List_of_apt_2_install_}" ];then
-    	($_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
-		($_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
-		$_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_}
+    	($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
+		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
+		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq ${List_of_apt_2_install_}
     else
     	show_wm "List_of_apt_2_install_ are empty"
     	sleep 1
@@ -206,14 +186,13 @@ upgrade_now()
 
 remove_package_with_error2info()
 {
-	localarray="$@"
-	for package in ${localarray}
-	do
-		if dpkg -s "${package}" >/dev/null 2>&1;then
-			show_im "Purging ${package}."
-			$_SUPERUSER apt-get purge -y "$package"
-		fi
-	done
+	packages="$@"
+	if [ -n "$packages" ];then
+		show_im "Removing ${packages}."
+		$_SUPERUSER apt-get purge -y $packages
+	else
+		show_wm "no packages to remove."
+	fi
 }
 
 remove_unnecessary_package_manager_stuff(){
@@ -260,14 +239,20 @@ _unattended_upgrades_()
 	fi
 }
 
+install_network_manager(){
+	network_manager_name="network-manager rfkill"
+	add_packages_2_install_list "${network_manager_name}"
+}
+
+install_lightdm_now(){
+	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
+	add_packages_2_install_list "${install_lightdm_}"
+}
+
 switch_to_network_manager(){
 	[ -f "${installer_phases}/switch_to_network_manager" ] && return
 	[ -f "/etc/network/interfaces.old" ] && return
 	show_m "runing switch_to_network_manager."
-	network_manager_name="network-manager"
-	show_im "switching to ${network_manager_name}"
-	add_packages_2_install_list "${network_manager_name}"
-	install_packages
 	show_im "create to interfaces file"
 	my-superuser tee "${temp_path}"/interfaces <<- 'EOF' >/dev/null
 	# This file describes the network interfaces available on your system
@@ -286,16 +271,32 @@ switch_to_network_manager(){
 	my-superuser mv "${temp_path}"/interfaces /etc/network/interfaces
 	show_im "Disable NetworkManager"
 	my-superuser sed -i 's/managed=.*/managed=false/g' /etc/NetworkManager/NetworkManager.conf
-	install_extra_Network_tools="rfkill"
-	show_im "installing ${install_extra_Network_tools}"
-	add_packages_2_install_list "${install_extra_Network_tools}"
-	install_packages
 	touch "${installer_phases}/switch_to_network_manager"
+}
+
+switch_lightdm_now(){
+	[ -f "${installer_phases}/switch_lightdm_now" ] && return
+	show_im "Switching to ( lightdm )."
+	
+	if [ -f "/etc/X11/default-display-manager" ];then
+		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
+		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
+	else
+		lightdm_does_not_exist=true
+	fi
+	
+	if [ "$lightdm_does_not_exist" = true  ];then
+		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1 || (show_em "failed to change default-display-manager")
+		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm || (show_em "failed to dpkg-reconfigure lightdm")
+	else
+		show_im "lightdm already exist."
+	fi
+	touch "${installer_phases}/switch_lightdm_now"
 }
 
 package_installed(){
 	package="${1:-}"
-	if dpkg -s "${package}" ;then
+	if grep -q "^$package" "$list_of_installed_apps_file_path";then
 		return 0
 	else
 		return 1
@@ -311,13 +312,11 @@ pre_package_manager_(){
 	aptfixer
 	enable_repo_
 	install_apt_fast || :
-	
 	if command -v apt-get >/dev/null 2>&1;then
 		PACKAGER="apt-get"
 	elif command -v apt-fast >/dev/null 2>&1;then
 		PACKAGER="apt-fast"
 	fi
 	upgrade_now
-	create_package_list
 	touch "${installer_phases}/pre_package_manager_"
 }
